name = "Hephaestus"
uuid = "5a5f24ea-65ec-4eaa-a0a3-a7b98033aea7"
authors = ["Damir Akchurin <AkchurinDA@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
Dates = "1.11.0"
DocStringExtensions = "0.9.3"
Memoization = "0.2.2"
Printf = "1.11.0"
StyledStrings = "1.11.0"


[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
HephaestusMakieExtension = "Makie"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]