name = "Hephaestus"
uuid = "5a5f24ea-65ec-4eaa-a0a3-a7b98033aea7"
authors = ["Damir Akchurin <AkchurinDA@gmail.com>"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
HephaestusMakieExtension = "Makie"

[compat]
Dates = "1.11.0"
DocStringExtensions = "0.9.3"
LinearAlgebra = "1.11.0"
Makie = "0.21"
Printf = "1.11.0"
StyledStrings = "1.11.0, 1"

[extras]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DifferentiationInterface", "ForwardDiff", "ReverseDiff"]
