name = "Hephaestus"
uuid = "6d460f16-3a26-426e-be05-f7feb4af91e7"
authors = ["Damir Akchurin <AkchurinDA@gmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
OrderedCollections = "1.7.0"
StyledStrings = "1.11.0"
