name = "Hephaestus"
uuid = "88b3b2ed-56ea-4eac-b1de-e42ac45953c8"
authors = ["Damir Akchurin <AkchurinDA@gmail.com>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
