name = "Hephaestus"
uuid = "88b3b2ed-56ea-4eac-b1de-e42ac45953c8"
authors = ["Damir Akchurin <AkchurinDA@gmail.com>"]
version = "0.1.0"

[deps]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
HephaestusMakieExt = "Makie"

[compat]
BlockDiagonals = "0.1"
DocStringExtensions = "0.9"
Makie = "0.21"
StyledStrings = "1"
julia = "1.10.0"
